version: "3.5"

x-mongo-defaults: &mongo-defaults
    image: "landisdesign/mongo-authenticated-cluster:4.0.3-xenial"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 250M
    volumes:
      - /data/db
      - $[MONGO_BACKUP_SRC]:/data/mongodb/backup
    networks:
      - webnet
    labels:
      com.michael-landis-awakening.mongodb.backup-name: "$[MONGO_BACKUP_NAME]"
      com.michael-landis-awakening.mongodb.replica-name: "$[MONGO_REPLICA_NAME]"
    environment:
      - MONGO_BACKUP_NAME=$[MONGO_BACKUP_NAME]
      - MONGO_REPLICA_NAME=$[MONGO_REPLICA_NAME]
      - MONGO_HOSTS=$[MONGO_HOSTS]
    secrets:
      - mongo
      - mongo_cluster

services:

  web:
    image: "landisdesign/tomcat-alpine:9.0.12"
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
    ports:
      - target: 8080
        published: $[WEB_SERVER_PORT]
    networks:
      - webnet

  visualizer:
    image: "dockersamples/visualizer:stable"
    ports:
      - target: 8080
        published: 8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet

$[loop:MONGO_HOSTS>MONGO_HOST]
  $[MONGO_HOST]:
    <<: *mongo-defaults
    hostname: $[MONGO_HOST]
    entrypoint: "tail -f /dev/null"

$[endloop:]
  mongo-shell:
    <<: *mongo-defaults
    image: "landisdesign/mongo-authenticated:4.0.3-xenial"
    entrypoint: "tail -f /dev/null"

  terminal:
    image: "bash:4.0"
    command: "tail -f /dev/null"
    volumes:
      - /:/host-machine
    networks:
      - webnet
    secrets:
      - mongo
      - mongo_cluster

networks:
  webnet:

secrets:
  mongo:
    external: true
    name: mongo_$[DOCKER_SECRET_VERSION]
  mongo_cluster:
    external: true
    name: mongo_cluster_$[DOCKER_SECRET_VERSION]
